export const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    price: 499,
    category: "electronics",
    image: "images/wirelessMouse.jpg",
  },
  {
    id: 2,
    name: "Wireless Keyboard",
    price: 1299,
    category: "electronics",
    image: "images/wirelessKeyboard.webp",
  },
  {
    id: 3,
    name: "Men's Casual T-Shirt",
    price: 699,
    category: "fashion",
    image: "images/tshirt.jpg",
  },
  {
    id: 4,
    name: "Women's Sneakers",
    price: 2499,
    category: "fashion",
    image: "images/shoes.jpg",
  },
  {
    id: 5,
    name: "Notebook Set",
    price: 199,
    category: "stationery",
    image: "images/notebook.jpg",
  },
  {
    id: 6,
    name: "Premium Pen Pack",
    price: 149,
    category: "stationery",
    image: "images/pens.jpg",
  },
  {
    id: 7,
    name: "Organic Brown Rice",
    price: 499,
    category: "groceries",
    image: "images/rice.jpg",
  },
  {
    id: 8,
    name: "Fresh Apples (1kg)",
    price: 199,
    category: "groceries",
    image: "images/apples.jpg",
  },
  {
    id: 9,
    name: "The Psychology of Money",
    price: 299,
    category: "books",
    image: "images/book.jpg",
  },
  {
    id: 10,
    name: "Atomic Habits",
    price: 349,
    category: "books",
    image: "images/book2.jpg",
  },
  {
    id: 11,
    name: "Wooden Chair",
    price: 1599,
    category: "furniture",
    image: "images/chair.jpg",
  },
  {
    id: 12,
    name: "Modern Study Table",
    price: 9499,
    category: "furniture",
    image: "images/table.jpg",
  },
  {
    id: 13,
    name: "Aloe Vera Face Wash",
    price: 249,
    category: "personal-care",
    image: "images/facewash.jpg",
  },
  {
    id: 14,
    name: "Herbal Shampoo",
    price: 299,
    category: "personal-care",
    image: "images/shampoo.jpg",
  },
];
